// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCey8DUUIkkQz0WFsYWTSk3omtxRm6u5S4',
    appId: '1:726729640309:web:b4dcbb381a6c1c51146b3c',
    messagingSenderId: '726729640309',
    projectId: 'dfea2-6e951',
    authDomain: 'dfea2-6e951.firebaseapp.com',
    storageBucket: 'dfea2-6e951.appspot.com',
    measurementId: 'G-2FKWBWKWPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw5eYOAK8Nmb2fwXviVfTA7MQvc4Y9WJU',
    appId: '1:726729640309:android:33fa9fa53feab643146b3c',
    messagingSenderId: '726729640309',
    projectId: 'dfea2-6e951',
    storageBucket: 'dfea2-6e951.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCEh3z7W3ssEGVezVAKxoR1QzbSXy8tE',
    appId: '1:726729640309:ios:afc3ab807e400a6d146b3c',
    messagingSenderId: '726729640309',
    projectId: 'dfea2-6e951',
    storageBucket: 'dfea2-6e951.appspot.com',
    iosClientId: '726729640309-oapoai43s75src7jo5hh7300366ap6lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dfea2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVCEh3z7W3ssEGVezVAKxoR1QzbSXy8tE',
    appId: '1:726729640309:ios:afc3ab807e400a6d146b3c',
    messagingSenderId: '726729640309',
    projectId: 'dfea2-6e951',
    storageBucket: 'dfea2-6e951.appspot.com',
    iosClientId: '726729640309-oapoai43s75src7jo5hh7300366ap6lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dfea2',
  );
}
